/* eslint no-undef: 0 */
export const FIREBASE_DB = _FIREBASE_DB_
export const FIREBASE_API_KEY = _FIREBASE_API_KEY_
export const FIREBASE_AUTH = _FIREBASE_AUTH_
export const FIREBASE_PROJECT_ID = _FIREBASE_PROJECT_ID_
export const FIREBASE_STORAGE = _FIREBASE_STORAGE_
export const FIREBASE_MESSAGE_ID = _FIREBASE_MESSAGE_ID_
